import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const euclidCircularB = localFont({
    src: [
        {
            path: "./fonts/EuclidCircularBRegular.woff",
            weight: "400",
        },
        {
            path: "./fonts/EuclidCircularBMedium.woff",
            weight: "500",
        },
        {
            path: "./fonts/EuclidCircularBSemiBold.woff",
            weight: "600",
        },
        {
            path: "./fonts/EuclidCircularBBold.woff",
            weight: "700",
        },
    ],
    variable: "--font-euclid-circular-b",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${euclidCircularB.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
